target:
  service: amlk8s
  name: itpeusp100cl
  vc: resrchvc

environment:
  image: ninja0/mmdet:latest

storage:
  # default:
  #   storage_account_name: njrr1
  #   container_name: v-jining
  output:
    storage_account_name: jianing
    container_name: v-jining
    mount_dir: /mnt/output
  data:
    storage_account_name: zdaxeu
    container_name: imagenet-zip
    mount_dir: /mnt/io

code:
  local_dir: $CONFIG_DIR

data:
  storage_id: data
  remote_dir: /mnt/io/coco2017

jobs:
  - name: test
    sku: G4
    sku_count: 2
    aml_mpirun:
      communicator: OpenMpi
      process_count_per_node: 4
    command:
      - set -x
      - echo $$PATH
      - sudo -E env "PATH=$$PATH" python run_mmdet_on_aml_dist.py --cfg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
